apiVersion: v1
kind: PersistentVolume
metadata:
  name: qpidd-storage-0
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/qpidd-storage-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qpidd-storage-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/qpidd-storage-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qpidd-storage-2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/qpidd-storage-2
