apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qdrouterd
  labels:
    app: qdrouterd
spec:
  replicas: 1
  template:
    metadata:
      name: qdrouterd
      labels:
        name: qdrouterd
    spec:
      containers:
        - image: scholzj/qpid-dispatch:0.6.0
          name: qdrouterd
          #imagePullPolicy: Always
          env:
            - name:  QDROUTERD_ADMIN_USERNAME
              value: admin
            - name:  QDROUTERD_ADMIN_PASSWORD
              value: "123456"
            - name: QDROUTERD_CONFIG_INSET
              value: |
                    connector {
                      name: shard_0
                      role: route-container
                      host: brokers-0.qpidd
                      port: 5672
                      saslUsername: admin
                      saslPassword: 123456
                      allowRedirect: no
                      idleTimeoutSeconds: 120
                    }

                    connector {
                      name: shard_1
                      role: route-container
                      host: brokers-1.qpidd
                      port: 5672
                      saslUsername: admin
                      saslPassword: 123456
                      allowRedirect: no
                      idleTimeoutSeconds: 120
                    }

                    connector {
                      name: shard_2
                      role: route-container
                      host: brokers-2.qpidd
                      port: 5672
                      saslUsername: admin
                      saslPassword: 123456
                      allowRedirect: no
                      idleTimeoutSeconds: 120
                    }

                    address {
                        prefix: shardedQueue
                        waypoint: yes
                    }

                    autoLink {
                        addr: shardedQueue
                        dir: in
                        connection: shard_0
                    }

                    autoLink {
                        addr: shardedQueue
                        dir: out
                        connection: shard_0
                    }

                    autoLink {
                        addr: shardedQueue
                        dir: in
                        connection: shard_1
                    }

                    autoLink {
                        addr: shardedQueue
                        dir: out
                        connection: shard_1
                    }

                    autoLink {
                        addr: shardedQueue
                        dir: in
                        connection: shard_2
                    }

                    autoLink {
                        addr: shardedQueue
                        dir: out
                        connection: shard_2
                    }
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 5671
              name: amqps
          #resources:
            #limits:
              #cpu: 500m
              #memory: 1Gi
            #requests:
              #cpu: 100m
              #memory: 256Mi
